import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { imageData } = await req.json();

    if (!imageData) {
      throw new Error("Image data is required");
    }

    // Récupérer la clé API Gemini depuis les secrets Supabase
    const geminiApiKey = Deno.env.get("GEMINI_API_KEY");
    if (!geminiApiKey) {
      throw new Error("GEMINI_API_KEY not configured");
    }

    // Convertir l'image base64 en format accepté par Gemini
    const base64Image = imageData.replace(/^data:image\/\w+;base64,/, "");

    // Appel à l'API Gemini Vision
    const geminiResponse = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${geminiApiKey}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: `Analyse cette carte grise française et extrait toutes les informations avec une précision maximale. 

Retourne UNIQUEMENT un objet JSON (sans markdown, sans backticks) avec ces champs EXACTEMENT :

{
  "E": "VIN complet (17 caractères)",
  "A": "Numéro d'immatriculation (format XX-XXX-XX)",
  "D1": "Marque du véhicule",
  "D2": "Type, variante, version",
  "D3": "Dénomination commerciale",
  "J": "Genre du véhicule (CTTE, VP, VASP, etc)",
  "J1": "Carrosserie (ex: FOURGON, BERLINE)",
  "K": "Numéro de réception",
  "P3": "Type de carburant",
  "P6": "Puissance fiscale (CV)",
  "P1": "Cylindrée (cm³)",
  "G": "Masse en ordre de marche (kg)",
  "F1": "PTAC (kg)",
  "F2": "PTRA (kg)",
  "U1": "Niveau sonore (dB)",
  "U2": "Vitesse de rotation du moteur (tr/min)",
  "V7": "CO2 (g/km)",
  "S1": "Nombre de places assises",
  "L": "Longueur (mm)",
  "B": "Largeur (mm)",
  "H": "Hauteur (mm)",
  "B1": "Date de première immatriculation",
  "confidence": 95
}

Instructions critiques :
- VIN (E) : 17 caractères EXACTS, vérifie la police pour différencier O/0, I/1
- Immatriculation (A) : Format exact avec tirets
- Tous les nombres SANS unités
- Date B1 au format DD/MM/YYYY
- confidence = ton niveau de confiance global (0-100)

IMPORTANT : Retourne UNIQUEMENT le JSON, sans texte avant ou après.`,
                },
                {
                  inline_data: {
                    mime_type: "image/jpeg",
                    data: base64Image,
                  },
                },
              ],
            },
          ],
          generationConfig: {
            temperature: 0.1,
            topK: 32,
            topP: 1,
            maxOutputTokens: 2048,
          },
        }),
      }
    );

    if (!geminiResponse.ok) {
      const errorText = await geminiResponse.text();
      console.error("Gemini API error:", errorText);
      throw new Error(`Gemini API error: ${geminiResponse.statusText}`);
    }

    const geminiData = await geminiResponse.json();
    console.log("Gemini response:", JSON.stringify(geminiData, null, 2));

    // Extraire le texte de la réponse
    const generatedText = geminiData.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!generatedText) {
      throw new Error("No text generated by Gemini");
    }

    // Parser le JSON depuis le texte généré (enlever les backticks markdown si présents)
    let cleanedText = generatedText.trim();
    cleanedText = cleanedText.replace(/^```json\s*/i, "").replace(/\s*```$/i, "");
    cleanedText = cleanedText.trim();

    const vehicleData = JSON.parse(cleanedText);

    // Validation basique
    if (!vehicleData.E || !vehicleData.A) {
      throw new Error("Missing critical data (VIN or Immatriculation)");
    }

    return new Response(
      JSON.stringify({
        success: true,
        data: vehicleData,
        raw_text: generatedText,
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  } catch (error) {
    console.error("Error in scan-carte-grise:", error);
    return new Response(
      JSON.stringify({
        success: false,
        error: error.message,
      }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
